version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
